ROIC_TABLE = 'Return on Investment Historical Data'
EQUITY_TABLE = 'Annual Share Holder Equity'
EPS_TABLE = 'Annual EPS'
CASH_TABLE = 'Annual Cash on Hand'
REVENUE_TABLE = 'Annual Revenue'
PE_TABLE = 'PE Ratio Historical Data'
BASIC_SHARES_OUTSTANDING_TABLE = 'Annual Basic Shares Outstanding'
BASIC_SHARES_LATEST_TEXT = 'Ross Stores annual basic shares outstanding for'